# Generated by Django 3.2.3 on 2021-05-30 07:03

from django.db import migrations, models
import django.db.models.deletion
import falconeye.characters.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_year', models.CharField(max_length=255, validators=[falconeye.characters.validators.birth_year_validator])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('n/a', 'Not Applicable'), ('unknown', 'Unknown')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('climate', models.CharField(max_length=255)),
                ('terrain', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('pilots', models.ManyToManyField(related_name='vehicles', to='characters.People')),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='home_world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.planet'),
        ),
    ]
